//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KontaktiMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broj
    {
        public string broj1 { get; set; }
        public string tip { get; set; }
        public string opis { get; set; }
        public int id_osoba { get; set; }
    
        public virtual Osoba Osoba { get; set; }
    }
}
